### ISSUE TITLE
Use ajax to send login request without changing pages

### ISSUE THREAD

**Issue by arizotaz** [EthanMorris2003/AlphaTeam#103]
Look into using AJAX to send the login request.  This allows you to give error messages such as "Invalid Password" on the login page without reloading or changing pages.  Right now, if something goes wrong It's hard to tell, the page just goes to the home screen.

A demo can be found in the upload menu where we use ajax to upload the file and get the progress

**Comment by jkriz2** [comment]
Reworked it to use AJAX, still needs some work on responding with what went wrong. It responds correctly and works fine but it's definitely done wrong, will be my next goal.
