### ISSUE TITLE
Settings page layout

### ISSUE THREAD

**Issue by ajoseph723** [EthanMorris2003/AlphaTeam#11]

**Comment by arizotaz** [comment]
Must contain changeable keyboard controls for lanes 1-5.  It is preferable if you can change the number of lanes with a variable.  We could technically have an infinite number of lanes.  There must also be an audio latency tester or link to the Audio Latency test.  See UIManager in the repo to understand how to switch between menus.

**Comment by arizotaz** [comment]
See settings.js for changing keybinds and options.

**Comment by arizotaz** [comment]
This issue has been open for too long, I have completed it
