### ISSUE TITLE
Improve method of gathering beatmap timestamps for user mp3s.

### ISSUE THREAD

**Issue by alexJM26** [EthanMorris2003/AlphaTeam#23]
This should have the following improvements.
- Be done using a method that processes the song data without it having to be played first. 
- Output the generated timestamps in the desired JSON format.
- Compute the criteria for peaks (beatmap timestamps) across intervals of the song rather than across the whole song.

**Comment by arizotaz** [comment]
Note:
    This can be done in any language of the developers choosing.  If you find a better way to accomplish the task using a binary file, we can upload the file to the webserver, process it with the binary, and send it back to the user.  Just like most image converting websites.  To sum it up, the language does not matter.
