### ISSUE TITLE
Find Music

### ISSUE THREAD

**Issue by arizotaz** [EthanMorris2003/AlphaTeam#32]
We need some songs that we can push through Alex's converter.  These will be demo songs.  We can work with difficulty later, but for now, find a bunch of songs that we can add to the program for the Demo.  10 is probably a good number, have fun with it, and definitely do the one that Delozier said not too

Copyright does not matter right now.

**Comment by bmyers60** [comment]
hot to go
sweet child of mine
please please please
sir duke
pink pony club
cotton eye joe
dynamite
radioactive
creep 
arms wide open

**Comment by arizotaz** [comment]
Thank you
