### ISSUE TITLE
Fix disappearing selections on main game menu. 

### ISSUE THREAD

**Issue by alexJM26** [EthanMorris2003/AlphaTeam#41]
When going to the website, the "Level Select", "Settings", "Multiplayer", and "About" buttons with disappear if you hover your mouse button over them but don't click on them.

**Comment by arizotaz** [comment]
Please comment the device you are using and the browser.  If possible, please post a video of this issue on the discord server.  I am not able to replicate the issue on my end

**Comment by arizotaz** [comment]
I was able to replicate the issue using the Firefox browser, we will tackle this issue later.  I am sure that I can find a CSS handle to change button design on only the firefox browser.  I have done it with IOS a ton of times.

**Comment by arizotaz** [comment]
Simple fix. The @-moz-document url-prefix() method is used to disable the scale transform on hover for only the firefox browser
