### ISSUE TITLE
Process and delete uploaded song files

### ISSUE THREAD

**Issue by alexJM26** [EthanMorris2003/AlphaTeam#47]
Add functionality that makes the beatmapGenerator python script process the uploaded mp3s. Then delete the mp3s after the script outputs the corresponding .json files into the levels folder.

**Comment by alexJM26** [comment]
Written Test:
1. Choose an mp3 file.
2. Navigate to the website's upload page.
3. Choose the mp3 with the "upload" button and hit "submit".
4. Check the state of the Levels Folder (/client/assets/game/keyboardhero/levels) to ensure there is a JSON file with the mp3's name and that the mp3 file no longer exists in that folder.

**Comment by arizotaz** [comment]
Now that testing is done, please create a written testing procedure first.  We will work on automatic testing later.

**Comment by alexJM26** [comment]
Updated Written Test for Uploading and Processing Songs:
1. Navigate to the website's "Upload Song" page.
2. Hit the upload button, choose an mp3 file from your computer, and press submit.
3. Confirm that the website enters the game, plays the uploaded mp3, and has generated tile corresponding to that mp3.
4. Confirm that the file was successfully uploaded and deleted via the terminal (two messages confirming this should be seen).
