### ISSUE TITLE
A file format for beat maps

### ISSUE THREAD

**Issue by arizotaz** [EthanMorris2003/AlphaTeam#9]
This file format must contain:
- File version
- The uploaded file name
- The uploaded file data
- An array for each track that contains the exact mili-second times for each note

**Comment by alexJM26** [comment]
The file format will be in JSON. An example is below. 
For the units field, 0 indicates seconds and 1 indicates milliseconds.

{
    "version": 1.0,
    "units": 0
    "song_title": "solopiano2",
    "beatmap_arrays": [
        { 
            "track": 0,
            "timestamps": [ 1.366, 2.3, 3.3, 5.233, 7.216, 8.15, 9.266, 11.35, 13.416, 15.183, 16, 17.56 ]
        },
        {
            "track": 1,
            "timestamps": [ 1.85, 4.25, 5.233, 6.05, 7.216, 8.833, 10.016, 11.35, 12.383, 14.85 ]
        },
        {
            "track": 2,
            "timestamps": [ 4.25, 7.616, 9.266, 11.35, 15.183 ]
        },
        {
            "track": 3,
            "timestamps": [ 1.366, 3.733, 4.033, 6.05, 12.383, 13.1, 17.56 ]
        }
    ],
    "data": "data:audio/wav;base64, ... base64EncodedMP3 ...",
}
